batch_size: 1024
best_epoch: 19
best_metric: 0.9618281090993659
catalog_file: catalog.txt
catalog_n: 3526
checkpoint: 19
checkpoint_metric: val_iou
data_dir: E:/Work_stuff/scatteringNet/data
depth: 4
device: cuda
encoder_depth: 4
encoder_hidden: 64
envelope_mix: 75
epochs: 20
finished_at: '2026-09-03T20:54:30'
gpu: NVIDIA GeForce GTX 1080
hidden: 64
knn_k: 16
knn_local_dim: null
latent_dim: null
lr: 0.001
max_files_per_shape: 2
n_faces: 256
n_files: 3526
n_meshes: 1763
n_points: 23409112
n_surface: 2048
n_test: 5053797
n_test_files: 706
n_test_meshes: 353
n_train: 18355315
n_train_files: 2820
n_train_meshes: 1410
n_val: 5053797
n_val_files: 706
n_val_meshes: 353
npz_catalog:
- glob: exports/dataset/cone_*.npz
  max_shapes: null
- glob: exports/dataset/cube_*.npz
  max_shapes: null
- glob: exports/dataset/cyl_*.npz
  max_shapes: null
- glob: exports/dataset/gear_*.npz
  max_shapes: null
- glob: exports/dataset/helix_*.npz
  max_shapes: null
- glob: exports/dataset/pipe_*.npz
  max_shapes: null
- glob: exports/dataset/platonic_*.npz
  max_shapes: null
- glob: exports/dataset/prism_*.npz
  max_shapes: null
- glob: exports/dataset/sphere_*.npz
  max_shapes: null
- glob: exports/dataset/torus_*.npz
  max_shapes: null
- glob: exports/dataset/extrude_*_nr1_*.npz
  max_shapes: 700
- glob: exports/dataset/extrude_*_nr3_*.npz
  max_shapes: 100
- glob: exports/dataset/extrude_*_nr4_*.npz
  max_shapes: 80
npz_glob: exports/dataset/*.npz
optimizer: adam
run_dir: runs/2026-09-03_15-59-37_prim_extrude_knn16_n2048
run_id: 2026-09-03_15-59-37_prim_extrude_knn16_n2048
run_name: prim_extrude_knn16_n2048
seed: 1
shape_encoder: surface
split: mesh
started_at: '2026-09-03T15:56:15'
total: 20
val_fraction: 0.2
wall: 4h 58m 14.98s
wall_seconds: 17894.983
