batch_size: 1024
best_epoch: 19
best_metric: 0.9590841710437925
catalog_file: catalog.txt
catalog_n: 5000
checkpoint: 19
checkpoint_metric: val_acc
data_dir: E:/Work_stuff/scatteringNet/data
depth: 6
device: cuda
epochs: 20
finished_at: '2026-08-31T01:25:50'
gpu: NVIDIA GeForce GTX 1080
hidden: 128
latent_dim: null
lr: 0.001
max_files_per_shape: 2
n_files: 5000
n_meshes: 2500
n_points: 11522442
n_surface: 1024
n_test: 2326679
n_test_files: 1000
n_test_meshes: 500
n_train: 9195763
n_train_files: 4000
n_train_meshes: 2000
n_val: 2326679
n_val_files: 1000
n_val_meshes: 500
npz_glob: exports/dataset/extrude_*_nr1_*.npz
optimizer: adam
run_dir: runs/2026-08-30_22-59-57_extrude_nr1_surface
run_id: 2026-08-30_22-59-57_extrude_nr1_surface
run_name: extrude_nr1_surface
seed: 1
shape_encoder: surface
split: mesh
started_at: '2026-08-30T22:57:53'
total: 20
val_fraction: 0.2
wall: 2h 27m 57.54s
wall_seconds: 8877.542
