batch_size: 1024
best_epoch: 9
best_metric: 0.977820990547167
catalog_file: catalog.txt
catalog_n: 2154
checkpoint: 9
checkpoint_metric: val_iou
data_dir: E:/Work_stuff/scatteringNet/data
depth: 4
device: cuda
epochs: 10
finished_at: '2026-09-16T20:21:15'
gpu: NVIDIA GeForce GTX 1080
hidden: 64
knn_k: 16
knn_local_dim: null
latent_dim: null
lr: 0.001
max_files_per_shape: 2
n_files: 2154
n_meshes: 1077
n_points: 33895373
n_surface: 1024
n_test: 6988662
n_test_files: 430
n_test_meshes: 215
n_train: 26906711
n_train_files: 1724
n_train_meshes: 862
n_val: 6988662
n_val_files: 430
n_val_meshes: 215
npz_catalog:
- glob: exports/dataset/cone_*.npz
  max_shapes: null
- glob: exports/dataset/cube_*.npz
  max_shapes: null
- glob: exports/dataset/cyl_*.npz
  max_shapes: null
- glob: exports/dataset/gear_*.npz
  max_shapes: null
- glob: exports/dataset/helix_*.npz
  max_shapes: null
- glob: exports/dataset/pipe_*.npz
  max_shapes: null
- glob: exports/dataset/platonic_*.npz
  max_shapes: null
- glob: exports/dataset/prism_*.npz
  max_shapes: null
- glob: exports/dataset/sphere_*.npz
  max_shapes: null
- glob: exports/dataset/torus_*.npz
  max_shapes: null
- glob: exports/dataset/extrude_*_nr1_*.npz
  max_shapes: 40
- glob: exports/dataset/extrude_*_nr4_*occupancy_s0.08*.npz
  max_shapes: 90
- glob: exports/dataset/extrude_*_nr5_*occupancy_s0.08*.npz
  max_shapes: null
npz_glob: exports/dataset/*.npz
optimizer: adam
run_dir: runs/2026-09-16_16-34-46_prim_nr45_knn16_n6_nosmooth_test_local_pc
run_id: 2026-09-16_16-34-46_prim_nr45_knn16_n6_nosmooth_test_local_pc
run_name: prim_nr45_knn16_n6_nosmooth_test_local_pc
seed: 1
shape_encoder: surface
split: mesh
started_at: '2026-09-16T16:33:31'
total: 10
val_fraction: 0.2
wall: 3h 47m 44.54s
wall_seconds: 13664.541
